//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estimador.LanguagesSupport {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Estimador.LanguagesSupport.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company:.
        /// </summary>
        internal static string AboutUS_Company_Descriptor {
            get {
                return ResourceManager.GetString("AboutUS_Company_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name:.
        /// </summary>
        internal static string AboutUS_Name_Descriptor {
            get {
                return ResourceManager.GetString("AboutUS_Name_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Fireboss....
        /// </summary>
        internal static string AboutUS_Title_Descriptor {
            get {
                return ResourceManager.GetString("AboutUS_Title_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version:.
        /// </summary>
        internal static string AboutUS_Version_Descriptor {
            get {
                return ResourceManager.GetString("AboutUS_Version_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base hours:.
        /// </summary>
        internal static string BaseHoursDescriptor {
            get {
                return ResourceManager.GetString("BaseHoursDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base (hours).
        /// </summary>
        internal static string Configuration_BaseHours_Descriptor {
            get {
                return ResourceManager.GetString("Configuration_BaseHours_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string Configuration_Controls_Columns_Category {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default value.
        /// </summary>
        internal static string Configuration_Controls_Columns_DefaultValue {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string Configuration_Controls_Columns_Delete {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string Configuration_Controls_Columns_Description {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effort.
        /// </summary>
        internal static string Configuration_Controls_Columns_Effort {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Effort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        internal static string Configuration_Controls_Columns_Pond {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Pond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control type.
        /// </summary>
        internal static string Configuration_Controls_Columns_Type {
            get {
                return ResourceManager.GetString("Configuration_Controls_Columns_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        internal static string Configuration_Controls_Descriptor {
            get {
                return ResourceManager.GetString("Configuration_Controls_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved estimations.
        /// </summary>
        internal static string Configuration_LoadTemplate_Filter_estm {
            get {
                return ResourceManager.GetString("Configuration_LoadTemplate_Filter_estm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template files.
        /// </summary>
        internal static string Configuration_LoadTemplate_Filter_etmp {
            get {
                return ResourceManager.GetString("Configuration_LoadTemplate_Filter_etmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price per hour.
        /// </summary>
        internal static string Configuration_PricePerHour_Descriptor {
            get {
                return ResourceManager.GetString("Configuration_PricePerHour_Descriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The estimation base is:.
        /// </summary>
        internal static string Configuration_RefreshTemplate_TooltipEstimationBase {
            get {
                return ResourceManager.GetString("Configuration_RefreshTemplate_TooltipEstimationBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour/s.
        /// </summary>
        internal static string Configuration_RefreshTemplate_TooltipUnit {
            get {
                return ResourceManager.GetString("Configuration_RefreshTemplate_TooltipUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This weight represents: .
        /// </summary>
        internal static string Configuration_RefreshTemplate_TooltipWeightRepresents {
            get {
                return ResourceManager.GetString("Configuration_RefreshTemplate_TooltipWeightRepresents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelled!.
        /// </summary>
        internal static string Configuration_SaveButton_AsyncCenceledMessage {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_AsyncCenceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved!.
        /// </summary>
        internal static string Configuration_SaveButton_AsyncSavedMessage {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_AsyncSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving....
        /// </summary>
        internal static string Configuration_SaveButton_AsyncSavingMessage {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_AsyncSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.Area.Project.Estimation.
        /// </summary>
        internal static string Configuration_SaveButton_DefaultFileName {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved estimations.
        /// </summary>
        internal static string Configuration_SaveButton_Filter_estm {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_Filter_estm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template files.
        /// </summary>
        internal static string Configuration_SaveButton_Filter_etmp {
            get {
                return ResourceManager.GetString("Configuration_SaveButton_Filter_etmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effort saved:.
        /// </summary>
        internal static string EffortSavedDescriptor {
            get {
                return ResourceManager.GetString("EffortSavedDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effort taken:.
        /// </summary>
        internal static string EffortTakenDescriptor {
            get {
                return ResourceManager.GetString("EffortTakenDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CATEGORY.
        /// </summary>
        internal static string Main_BuildGantt_ExportPdf_CategoryHeader {
            get {
                return ResourceManager.GetString("Main_BuildGantt_ExportPdf_CategoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MONTH.
        /// </summary>
        internal static string Main_BuildGantt_ExportPdf_MonthHeader {
            get {
                return ResourceManager.GetString("Main_BuildGantt_ExportPdf_MonthHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour/s.
        /// </summary>
        internal static string Main_CustomControl_EstimatedWeightChanges_Unit {
            get {
                return ResourceManager.GetString("Main_CustomControl_EstimatedWeightChanges_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.Area.Project.Estimation.
        /// </summary>
        internal static string Main_ExportPdf_DefaultFileNameTemplate {
            get {
                return ResourceManager.GetString("Main_ExportPdf_DefaultFileNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimated report.
        /// </summary>
        internal static string Main_ExportPdf_Filter {
            get {
                return ResourceManager.GetString("Main_ExportPdf_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BASEHOURS.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_BaseHours {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_BaseHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Category.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_Category {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effort saved.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_EfforSaved {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_EfforSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Effort taken.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_EffortTaken {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_EffortTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours saved.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_HoursSaved {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_HoursSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hours taken.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_HoursTaken {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_HoursTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRICE PER HOUR.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_PricePerHour {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_PricePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUB TOTAL EFFORT.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_SubTotalEffort {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_SubTotalEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SUB TOTAL HOURS.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_SubTotalHours {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_SubTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL HOURS.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_TotalHours {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_TotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTALPRICE.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_TotalPrice {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Do you want to print prices?.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_WarningPrintPrices {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_WarningPrintPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning!.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_WarningPrintPricesTitle {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_WarningPrintPricesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weight.
        /// </summary>
        internal static string Main_GetBodyContent1_ExportPdf_Weight {
            get {
                return ResourceManager.GetString("Main_GetBodyContent1_ExportPdf_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Working hours estimation.
        /// </summary>
        internal static string Main_GetHeader_ExportPdf_Title {
            get {
                return ResourceManager.GetString("Main_GetHeader_ExportPdf_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved estimations.
        /// </summary>
        internal static string Main_LoadTemplate_Filter_estm {
            get {
                return ResourceManager.GetString("Main_LoadTemplate_Filter_estm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template files.
        /// </summary>
        internal static string Main_LoadTemplate_Filter_etmp {
            get {
                return ResourceManager.GetString("Main_LoadTemplate_Filter_etmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customer.Area.Project.Estimation.
        /// </summary>
        internal static string Main_SaveButton_DefaultFileNameTemplate {
            get {
                return ResourceManager.GetString("Main_SaveButton_DefaultFileNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved estimations.
        /// </summary>
        internal static string Main_SaveButton_Filter_estm {
            get {
                return ResourceManager.GetString("Main_SaveButton_Filter_estm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Project&apos;s estimator.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open from....
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price per hour:.
        /// </summary>
        internal static string PricePerHourDescriptor {
            get {
                return ResourceManager.GetString("PricePerHourDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as....
        /// </summary>
        internal static string SaveDialogTitle {
            get {
                return ResourceManager.GetString("SaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total price:.
        /// </summary>
        internal static string TotalPriceDescriptor {
            get {
                return ResourceManager.GetString("TotalPriceDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total time:.
        /// </summary>
        internal static string TotalTimeDescriptor {
            get {
                return ResourceManager.GetString("TotalTimeDescriptor", resourceCulture);
            }
        }
    }
}
